// QuickFIX/J + QuickFIX/n session config generator (spec §36, phase 6).
// Pure functions so the output is unit-testable; the page adds copy +
// download around them.

export interface QuickFixConfigInput {
  // The USER's engine role (the side this config is written for).
  role: "initiator" | "acceptor";
  beginString: string;
  senderCompId: string;
  targetCompId: string;
  host: string; // initiator only
  port: number;
  heartBtInt: number;
  dataDictionary: string;
}

const BEGIN_TO_DICT: Record<string, string> = {
  "FIX.4.0": "FIX40.xml",
  "FIX.4.2": "FIX42.xml",
  "FIX.4.4": "FIX44.xml",
  "FIX.5.0SP2": "FIX50SP2.xml",
};

export function defaultDictionary(beginString: string): string {
  return BEGIN_TO_DICT[beginString] ?? "FIX44.xml";
}

function sessionBlock(input: QuickFixConfigInput, engine: "j" | "n"): string {
  const lines = [
    "[SESSION]",
    `BeginString=${input.beginString}`,
    `SenderCompID=${input.senderCompId}`,
    `TargetCompID=${input.targetCompId}`,
    `ConnectionType=${input.role}`,
  ];
  if (input.role === "initiator") {
    lines.push(`SocketConnectHost=${input.host}`);
    lines.push(`SocketConnectPort=${input.port}`);
  } else {
    lines.push(`SocketAcceptPort=${input.port}`);
  }
  lines.push(`DataDictionary=${input.dataDictionary}`);
  if (engine === "n") {
    // QuickFIX/n samples conventionally pin a 24h session schedule.
    lines.push("StartTime=00:00:00");
    lines.push("EndTime=00:00:00");
  } else {
    lines.push("ReconnectInterval=30");
  }
  return lines.join("\n");
}

// buildQuickFixJ renders a QuickFIX/J (.cfg) session config.
export function buildQuickFixJ(input: QuickFixConfigInput): string {
  return [
    "# QuickFIX/J session config — generated by FixLab (simulation environment, not a live trading venue).",
    "[DEFAULT]",
    `ConnectionType=${input.role}`,
    `HeartBtInt=${input.heartBtInt}`,
    "FileStorePath=store",
    "FileLogPath=log",
    "",
    sessionBlock(input, "j"),
    "",
  ].join("\n");
}

// buildQuickFixN renders a QuickFIX/n (.cfg) session config.
export function buildQuickFixN(input: QuickFixConfigInput): string {
  return [
    "# QuickFIX/n session config — generated by FixLab (simulation environment, not a live trading venue).",
    "[DEFAULT]",
    `ConnectionType=${input.role}`,
    `HeartBtInt=${input.heartBtInt}`,
    "FileStorePath=store",
    "FileLogPath=log",
    "",
    sessionBlock(input, "n"),
    "",
  ].join("\n");
}
